function [raw, filtered] = specifically_load_from_csv(input_file_path)
%specifically_load_from_csv Za³aduj dane z .csv dla konkretnych plików
%   Tworzy zmienne filtered i raw by mog³y byæ potem zapisane do struktur
% Kod zosta³ wygenerowany na podstawie manualnego podejœcia

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: input_file_path
%
% Auto-generated by MATLAB on 12-Mar-2020 20:32:03

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "raw", "filtered"];
opts.SelectedVariableNames = ["raw", "filtered"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(input_file_path, opts);

%% Convert to output type
raw = tbl.raw;
filtered = tbl.filtered;

%% Clear temporary variables
clear opts tbl

end

